      <!--#include file="./HomeController.asp" -->
      <!--#include file="./PlantController.asp" -->
      <!--#include file="./FailureController.asp" -->
      <!--#include file="./GroupsController.asp" -->
      <!--#include file="./UserController.asp" -->
      <!--#include file="./OverviewController.asp" -->
      <!--#include file="./AnalyzeController.asp" -->
      <!--#include file="./Tier1Controller.asp" -->
      <!--#include file="./WarehouseController.asp" -->
      <!--#include file="./SiteController.asp" -->
      <!--#include file="./SupplierController.asp" -->
      <!--#include file="./ModuleController.asp" -->
      <!--#include file="./SpareController.asp" -->
      <!--#include file="./Tier3Controller.asp" -->
      <!--#include file="./Tier2Controller.asp" -->
      <!--#include file="./CartController.asp" -->
      <!--#include file="./NearController.asp" -->
      <!--#include file="./MasterController.asp" -->
      <!--#include file="./BookingController.asp" -->
      <!--#include file="./ReportController.asp" -->
      <!--#include file="./OrderPropController.asp" -->
      <!--#include file="./QuoteController.asp" -->
      <!--#include file="./OrderController.asp" -->
      <!--#include file="./BoxController.asp" -->
      <!--#include file="./MailController.asp" -->
      <!--#include file="./CategorieController.asp" -->
      <!--#include file="./StatController.asp" -->
      <!--#include file="./StandController.asp" -->

      <%
      Public Controllers
      Set Controllers = Server.CreateObject("Scripting.Dictionary")
      Controllers.Add "homecontroller", ""
      Controllers.Add "plantcontroller", ""
      Controllers.Add "failurecontroller", ""
      Controllers.Add "groupscontroller", ""
      Controllers.Add "usercontroller", ""
      Controllers.Add "overviewcontroller", ""
      Controllers.Add "analyzecontroller", ""
      Controllers.Add "tier1controller", ""
      Controllers.Add "warehousecontroller", ""
      Controllers.Add "sitecontroller", ""
      Controllers.Add "suppliercontroller", ""
      Controllers.Add "modulecontroller", ""
      Controllers.Add "sparecontroller", ""
      Controllers.Add "tier3controller", ""
      Controllers.Add "tier2controller", ""
      Controllers.Add "cartcontroller", ""
      Controllers.Add "nearcontroller", ""
      Controllers.Add "mastercontroller", ""
      Controllers.Add "bookingcontroller", ""
      Controllers.Add "reportcontroller", ""
      Controllers.Add "orderpropcontroller", ""
      Controllers.Add "quotescontroller", ""
      Controllers.Add "ordercontroller", ""
      Controllers.Add "boxcontroller", ""
      Controllers.Add "mailcontroller", ""
      Controllers.Add "categoriecontroller", ""
      Controllers.Add "statcontroller", ""
      Controllers.Add "standcontroller", "" 
      %>